---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.4" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.4.2" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
addons:
      code_climate:
                repo_token: 1d699cad8d8d5a2ebbe437105276e862e3acd77fbd635a7225c50476b36e8c5a
